---

- name: users > Change Influx users password
  command: >
    {{ manala_influxdb_influx_bin }} 
    {{ katmai_influxdb_enable_ssl | default(omit) }} 
    {{ katmai_influxdb_enable_selfsigned_ssl | default(omit) }} 
    -host {{ katmai_influxdb_host }} 
    {{ ('-username ' + katmai_influxdb_username) if katmai_influxdb_username is defined else '' }} 
    {{ ('-password ' + katmai_influxdb_password) if katmai_influxdb_password is defined else '' }} 
    -execute "SET PASSWORD FOR {{ item.name }} = '{{ item.password }}'"
  with_items: "{{ influxdb_change_password }}"
  changed_when: false
