---

- name: privileges > Setup Influx privileges
  command: >
    {{ manala_influxdb_influx_bin }} 
    {{ katmai_influxdb_enable_ssl | default(omit) }} 
    {{ katmai_influxdb_enable_selfsigned_ssl | default(omit) }} 
    -host {{ katmai_influxdb_host }} 
    {{ ('-username ' + katmai_influxdb_username) if katmai_influxdb_username is defined else '' }} 
    {{ ('-password ' + katmai_influxdb_password) if katmai_influxdb_password is defined else '' }} 
    -execute 'GRANT {{ item.grant }} ON {{ item.database }} TO {{ item.user }}'
  with_items: "{{ manala_influxdb_privileges }}"
  changed_when: false
