---

- name: databases > Remove Influx databases
  command: >
    {{ manala_influxdb_influx_bin }} 
    {{ katmai_influxdb_enable_ssl | default(omit) }} 
    {{ katmai_influxdb_enable_selfsigned_ssl | default(omit) }} 
    -host {{ katmai_influxdb_host }} 
    {{ ('-username ' + katmai_influxdb_username) if katmai_influxdb_username is defined else '' }} 
    {{ ('-password ' + katmai_influxdb_password) if katmai_influxdb_password is defined else '' }} 
    -execute 'DROP DATABASE {{ item.database }}'
  with_items: "{{ influxdb_remove_db }}"
  changed_when: false

- name: users > Remove Influx users
  command: >
    {{ manala_influxdb_influx_bin }} 
    {{ katmai_influxdb_enable_ssl | default(omit) }} 
    {{ katmai_influxdb_enable_selfsigned_ssl | default(omit) }} 
    -host {{ katmai_influxdb_host }} 
    {{ ('-username ' + katmai_influxdb_username) if katmai_influxdb_username is defined else '' }} 
    {{ ('-password ' + katmai_influxdb_password) if katmai_influxdb_password is defined else '' }} 
    -execute "DROP USER \"{{ item.user }}\""
  with_items: "{{ influxdb_remove_user }}"
  changed_when: false
